export const GET_ALL_CATEGORIES_REQUEST = "GET_ALL_CATEGORIES_REQUEST";
export const GET_ALL_CATEGORIES_SUCCESS = "GET_ALL_CATEGORIES_SUCCESS";
export const GET_ALL_CATEGORIES_FAILURE = "GET_ALL_CATEGORIES_FAILURE";

export const GET_CATEGORY_BY_ID_REQUEST = "GET_CATEGORY_BY_ID_REQUEST";
export const GET_CATEGORY_BY_ID_SUCCESS = "GET_CATEGORY_BY_ID_SUCCESS";
export const GET_CATEGORY_BY_ID_FAILURE = "GET_CATEGORY_BY_ID_FAILURE";

export const SEARCH_CATEGORY_REQUEST = "SEARCH_CATEGORY_REQUEST";
export const SEARCH_CATEGORY_SUCCESS = "SEARCH_CATEGORY_SUCCESS";
export const SEARCH_CATEGORY_FAILURE = "SEARCH_CATEGORY_FAILURE";

export const GET_POPULAR_CATEGORIES_REQUEST = "GET_POPULAR_CATEGORIES_REQUEST";
export const GET_POPULAR_CATEGORIES_SUCCESS = "GET_POPULAR_CATEGORIES_SUCCESS";
export const GET_POPULAR_CATEGORIES_FAILURE = "GET_POPULAR_CATEGORIES_FAILURE";
