export const GET_USER_READING_LISTS_REQUEST = "GET_USER_READING_LISTS_REQUEST";
export const GET_USER_READING_LISTS_SUCCESS = "GET_USER_READING_LISTS_SUCCESS";
export const GET_USER_READING_LISTS_FAILURE = "GET_USER_READING_LISTS_FAILURE";

export const GET_PUBLIC_READING_LISTS_REQUEST = "GET_PUBLIC_READING_LISTS_REQUEST";
export const GET_PUBLIC_READING_LISTS_SUCCESS = "GET_PUBLIC_READING_LISTS_SUCCESS";
export const GET_PUBLIC_READING_LISTS_FAILURE = "GET_PUBLIC_READING_LISTS_FAILURE";

export const CREATE_READING_LIST_REQUEST = "CREATE_READING_LIST_REQUEST";
export const CREATE_READING_LIST_SUCCESS = "CREATE_READING_LIST_SUCCESS";
export const CREATE_READING_LIST_FAILURE = "CREATE_READING_LIST_FAILURE";

export const UPDATE_READING_LIST_REQUEST = "UPDATE_READING_LIST_REQUEST";
export const UPDATE_READING_LIST_SUCCESS = "UPDATE_READING_LIST_SUCCESS";
export const UPDATE_READING_LIST_FAILURE = "UPDATE_READING_LIST_FAILURE";

export const DELETE_READING_LIST_REQUEST = "DELETE_READING_LIST_REQUEST";
export const DELETE_READING_LIST_SUCCESS = "DELETE_READING_LIST_SUCCESS";
export const DELETE_READING_LIST_FAILURE = "DELETE_READING_LIST_FAILURE";

export const ADD_BOOK_TO_LIST_REQUEST = "ADD_BOOK_TO_LIST_REQUEST";
export const ADD_BOOK_TO_LIST_SUCCESS = "ADD_BOOK_TO_LIST_SUCCESS";
export const ADD_BOOK_TO_LIST_FAILURE = "ADD_BOOK_TO_LIST_FAILURE";

export const REMOVE_BOOK_FROM_LIST_REQUEST = "REMOVE_BOOK_FROM_LIST_REQUEST";
export const REMOVE_BOOK_FROM_LIST_SUCCESS = "REMOVE_BOOK_FROM_LIST_SUCCESS";
export const REMOVE_BOOK_FROM_LIST_FAILURE = "REMOVE_BOOK_FROM_LIST_FAILURE";
