export const GET_REVIEWS_BY_BOOK_REQUEST = 'GET_REVIEWS_BY_BOOK_REQUEST';
export const GET_REVIEWS_BY_BOOK_SUCCESS = 'GET_REVIEWS_BY_BOOK_SUCCESS';
export const GET_REVIEWS_BY_BOOK_FAILURE = 'GET_REVIEWS_BY_BOOK_FAILURE';

export const GET_REVIEWS_BY_USER_REQUEST = 'GET_REVIEWS_BY_USER_REQUEST';
export const GET_REVIEWS_BY_USER_SUCCESS = 'GET_REVIEWS_BY_USER_SUCCESS';
export const GET_REVIEWS_BY_USER_FAILURE = 'GET_REVIEWS_BY_USER_FAILURE';

export const CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST';
export const CREATE_REVIEW_SUCCESS = 'CREATE_REVIEW_SUCCESS';
export const CREATE_REVIEW_FAILURE = 'CREATE_REVIEW_FAILURE';

export const UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAILURE = 'UPDATE_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';

export const GET_RECENT_REVIEWS_REQUEST = 'GET_RECENT_REVIEWS_REQUEST';
export const GET_RECENT_REVIEWS_SUCCESS = 'GET_RECENT_REVIEWS_SUCCESS';
export const GET_RECENT_REVIEWS_FAILURE = 'GET_RECENT_REVIEWS_FAILURE';
