export const GET_ALL_BOOKS_REQUEST = "GET_ALL_BOOKS_REQUEST";
export const GET_ALL_BOOKS_SUCCESS = "GET_ALL_BOOKS_SUCCESS";
export const GET_ALL_BOOKS_FAILURE = "GET_ALL_BOOKS_FAILURE";

export const GET_BOOK_REQUEST = "GET_BOOK_REQUEST";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILURE = "GET_BOOK_FAILURE";

export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILURE = "CREATE_BOOK_FAILURE";

export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_FAILURE = "UPDATE_BOOK_FAILURE";

export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILURE = "DELETE_BOOK_FAILURE";

export const SEARCH_BOOKS_REQUEST = "SEARCH_BOOKS_REQUEST";
export const SEARCH_BOOKS_SUCCESS = "SEARCH_BOOKS_SUCCESS";
export const SEARCH_BOOKS_FAILURE = "SEARCH_BOOKS_FAILURE";

export const GET_TOP_RATED_BOOKS_REQUEST = "GET_TOP_RATED_BOOKS_REQUEST";
export const GET_TOP_RATED_BOOKS_SUCCESS = "GET_TOP_RATED_BOOKS_SUCCESS";
export const GET_TOP_RATED_BOOKS_FAILURE = "GET_TOP_RATED_BOOKS_FAILURE";

export const GET_MOST_REVIEWED_BOOKS_REQUEST = "GET_MOST_REVIEWED_BOOKS_REQUEST";
export const GET_MOST_REVIEWED_BOOKS_SUCCESS = "GET_MOST_REVIEWED_BOOKS_SUCCESS";
export const GET_MOST_REVIEWED_BOOKS_FAILURE = "GET_MOST_REVIEWED_BOOKS_FAILURE";

export const GET_BOOKS_BY_AUTHOR_REQUEST = "GET_BOOKS_BY_AUTHOR_REQUEST";
export const GET_BOOKS_BY_AUTHOR_SUCCESS = "GET_BOOKS_BY_AUTHOR_SUCCESS";
export const GET_BOOKS_BY_AUTHOR_FAILURE = "GET_BOOKS_BY_AUTHOR_FAILURE";

export const GET_BOOKS_BY_CATEGORY_REQUEST = "GET_BOOKS_BY_CATEGORY_REQUEST";
export const GET_BOOKS_BY_CATEGORY_SUCCESS = "GET_BOOKS_BY_CATEGORY_SUCCESS";
export const GET_BOOKS_BY_CATEGORY_FAILURE = "GET_BOOKS_BY_CATEGORY_FAILURE";
