export const GET_ALL_AUTHORS_REQUEST = "GET_ALL_AUTHORS_REQUEST";
export const GET_ALL_AUTHORS_SUCCESS = "GET_ALL_AUTHORS_SUCCESS";
export const GET_ALL_AUTHORS_FAILURE = "GET_ALL_AUTHORS_FAILURE";

export const GET_AUTHOR_REQUEST = "GET_AUTHOR_REQUEST";
export const GET_AUTHOR_SUCCESS = "GET_AUTHOR_SUCCESS";
export const GET_AUTHOR_FAILURE = "GET_AUTHOR_FAILURE";

export const CREATE_AUTHOR_REQUEST = "CREATE_AUTHOR_REQUEST";
export const CREATE_AUTHOR_SUCCESS = "CREATE_AUTHOR_SUCCESS";
export const CREATE_AUTHOR_FAILURE = "CREATE_AUTHOR_FAILURE";


export const UPDATE_AUTHOR_REQUEST = "UPDATE_AUTHOR_REQUEST";
export const UPDATE_AUTHOR_SUCCESS = "UPDATE_AUTHOR_SUCCESS";
export const UPDATE_AUTHOR_FAILURE = "UPDATE_AUTHOR_FAILURE";


export const DELETE_AUTHOR_REQUEST = "DELETE_AUTHOR_REQUEST";
export const DELETE_AUTHOR_SUCCESS = "DELETE_AUTHOR_SUCCESS";
export const DELETE_AUTHOR_FAILURE = "DELETE_AUTHOR_FAILURE";

export const SEARCH_AUTHORS_REQUEST = "SEARCH_AUTHORS_REQUEST";
export const SEARCH_AUTHORS_SUCCESS = "SEARCH_AUTHORS_SUCCESS";
export const SEARCH_AUTHORS_FAILURE = "SEARCH_AUTHORS_FAILURE";


export const GET_MOST_PRODUCTIVE_AUTHORS_REQUEST = "GET_MOST_PRODUCTIVE_AUTHORS_REQUEST";
export const GET_MOST_PRODUCTIVE_AUTHORS_SUCCESS = "GET_MOST_PRODUCTIVE_AUTHORS_SUCCESS";
export const GET_MOST_PRODUCTIVE_AUTHORS_FAILURE = "GET_MOST_PRODUCTIVE_AUTHORS_FAILURE";
